services:
  backend_ia:
    build: ./backend_ia
    container_name: backend_ia
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --reload --port 9000
    ports:
      - "9000:9000"
    volumes:
      - ./backend_ia:/app
    networks:
      - bigdata-net

  backend_node:
    build: ./backend_node  
    container_name: backend_node
    working_dir: /app
    command: nodemon server.js  
    ports:
      - "4000:4000"
    volumes:
      - ./backend_node:/app
      - node-modules-back:/app/node_modules
    networks:
      - bigdata-net

  frontend:
    build: ./frontend  
    container_name: frontend
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0  
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node-modules-front:/app/node_modules
    networks:
      - bigdata-net

volumes:
  node-modules-back:
  node-modules-front:

networks:
  bigdata-net:
    external: true
